dist: trusty
sudo: required

language: csharp
solution: BriskChat.sln

notifications:
  email:
    on_failure: change # default: always

# Fix for tests from https://github.com/travis-ci/travis-ci/issues/8866
addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

mono:
  #- 3.8.0
  - 3.10.0
  - 3.12.0
  - latest
  #- none

# .NET Core SDK version
dotnet: 2.1.105

before_script:
  - dotnet restore

script:
  - dotnet build
  - dotnet test ./BriskChat.BusinessLogic.Tests
  - dotnet publish -c Release
