dist: trusty
sudo: required

language: csharp
solution: BriskChat.sln

notifications:
  email:
    on_failure: change # default: always

mono:
  #- 3.8.0
  - 3.10.0
  - 3.12.0
  - latest
  #- none

# .NET Core SDK version
dotnet: 2.0.3

before_script:
  - dotnet restore

script:
  - dotnet build ./TrollChat.DataAccess
  - dotnet build ./TrollChat.BusinessLogic
  - dotnet build ./TrollChat.BusinessLogic.Tests
  - dotnet test ./TrollChat.BusinessLogic.Tests
  - dotnet test
