dist: trusty
sudo: required

language: csharp
solution: BriskChat.sln

notifications:
  email:
    on_failure: change # default: always

mono:
  #- 3.8.0
  - 3.10.0
  - 3.12.0
  - latest
  #- none

# .NET Core SDK version
dotnet: 2.1.105

before_script:
  - dotnet restore

script:
  - dotnet build
  - dotnet test ./TrollChat.BusinessLogic.Tests
  - dotnet publish -c Release
